version: '3.6'

services:
  php:
    container_name: mage2.4_php
    build:
      context: .
      dockerfile: ./docker/build/php/Dockerfile
    image: php_composer:7.3.0-fpm-alpine
    volumes:
      - ./web:/src
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/composer:/root/.composer
    links:
      - mysql
      - mailhog

  nginx:
    container_name: mage2.4_nginx
    image: nginx:1.17.6-alpine
    volumes:
      - ./web:/src
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - php

  mysql:
    container_name: mage2.4_mysql
    image: mysql:5.7.28
    volumes:
      - ./docker/volumes/mysql/data:/var/lib/mysql
      - ./docker/volumes/mysql/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mage123
      MYSQL_USER: mage
      MYSQL_PASSWORD: mage
      MYSQL_DATABASE: mage
    ports:
      - 3306:3306

  elasticsearch:
    container_name: mage2.4_elastic_7.6.2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./docker/volumes/es/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: mage2.4_kibana_7.6.2
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - 5601:5601
    links:
      - elasticsearch

  mailhog:
    container_name: mage2.4_mailhog_v1.0.1
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'mage2.4_rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

  redis:
    container_name: mage2.4_redis
    image: "redis"
    ports:
      - "6379:6379"
